import HeaderContainer from '../components/Header';
import style from '../styles/Layouts.module.scss';
import { AppstoreOutlined, MailOutlined, SettingOutlined } from '@ant-design/icons';
import Head from 'next/head';
import { Layout, Menu , Card, Row, Col } from 'antd';
import AddModal from '../components/AddModal';
import HistoryRow from '../components/HistoryRow';

const {  Footer, Sider, Content, Header  } = Layout;
const { SubMenu } = Menu;
const MainLayout = ({children, props}) => {
   const  handleClick = e => {
        console.log('click ', e);
      };
     
    return (
        <Layout>
         <Head>
            <title>LITE SKLAD</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
        <Header className={style.headerAntd}>
        <Row justify="center" align="top">
                <Col span={18}>
                    <HeaderContainer/>
                </Col>
                 
            </Row>
            
        </Header>
        <Layout>
     
        <Content className={style.headerAntd__content}>
        <Row justify="center" align="top">
       
      <Col span={14}>
       {children} 
      </Col>
      <Col span={4}>
        <Card> <h1>Последние изменения</h1>
          <HistoryRow/>
        
         </Card>
      </Col>
      </Row>
          
        </Content>
        </Layout>
       
            
           <Footer>
               Footer
               </Footer>
        </Layout>
    );
};


export default MainLayout;