import HeaderContainer from '../components/Header';
import style from '../styles/Layouts.module.scss';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import { Layout} from 'antd';
import SiderCustom from '../components/SiderCustom';
import { useRouter } from 'next/router'
import { LOGIN_ROUTE, LIST_ROUTE } from '../utils/routers';
const {  Footer, Sider,  Content, Header  } = Layout;

const MainLayout = ({children, props}) => {
  const router = useRouter();
  const [collapsed, setCollapsed] = useState(true);
  const [login, setLogin] = useState(null);
  useEffect(() => {
    if(!localStorage.getItem('user')){
      setLogin(null);
      router.push(LOGIN_ROUTE);
    }else{
      setLogin(JSON.parse(localStorage.getItem('user')));
     
    }
  },[]);


    const logOut = () => {
      localStorage.removeItem('user');
      setLogin(null);
      router.push('/');
    }
  
    return (
    <Layout style={{minHeight: '100vh'}}>
         <Head>
            <title>LITE SKLAD</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
        <Header className={style.headerAntd}>
                    <HeaderContainer login={login} logout = {logOut} />
        </Header>
        <Layout >
          <Sider collapsible collapsed={collapsed} onCollapse={()=>setCollapsed(!collapsed)} >
             <SiderCustom collapsed={collapsed}/>
          </Sider>
         
          <Layout style={{ padding: '0 24px 24px' }}>
            <Content>
                    {children} 
            </Content>
          </Layout>
      
        </Layout>
        <Footer>
               Footer
        </Footer>
    </Layout>
    );
};


export default MainLayout;